import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {isLanguage,normalizeLanguage,safeReturnTo,validateSignUp,validateSignIn,validateResendConfirmation,isValidEmail,isAuthErrorReason} from "../lib/auth.ts";import {isSafeUsername,profileAvatarInitial,PUBLIC_PROFILE_FIELDS,validateProfileUpdate} from "../lib/profile.ts";import {shouldCloseUserMenuForKey,userMenuAvatarInitial,userMenuButtonState,userMenuLabels,userMenuProfileHref} from "../lib/user-menu.ts";import {isPostCategory,isSafePostId,POST_CATEGORIES,postAvatarInitial,postCategoryLabel,validatePostInput} from "../lib/posts.ts";
import {postLanguageLabel} from "../lib/posts.ts";
import {commentAvatarInitial,commentCountLabel,toPublicComments,validateCommentInput} from "../lib/comments.ts";
test("CN valid",()=>assert.equal(isLanguage("CN"),true));test("KR valid",()=>assert.equal(isLanguage("KR"),true));test("zh invalid",()=>assert.equal(isLanguage("zh"),false));test("ko invalid",()=>assert.equal(isLanguage("ko"),false));test("en invalid",()=>assert.equal(isLanguage("en"),false));test("null invalid",()=>assert.equal(isLanguage(null),false));test("normalize KR",()=>assert.equal(normalizeLanguage("KR"),"KR"));test("normalize CN",()=>assert.equal(normalizeLanguage("CN"),"CN"));test("normalize unknown",()=>assert.equal(normalizeLanguage("x"),"CN"));
for(const [n,v,e] of [["root","/","/"],["profile","/profile","/profile"],["query","/a?x=1","/a?x=1"],["slashes","//evil","/"],["https","https://evil","/"],["http","http://evil","/"],["backslash","/\\evil","/"],["control","/a\n","/"],["encoded","/%2f%2fevil","/"],["double","/%252f%252fevil","/"],["empty","","/"],["null",null,"/"]])test(`return ${n}`,()=>assert.equal(safeReturnTo(v),e));
const good={username:"valid_user",displayName:"Name",email:"a@b.com",password:"password1",confirmPassword:"password1",preferredLanguage:"CN"};test("signup CN",()=>assert.equal(validateSignUp(good),null));test("signup KR",()=>assert.equal(validateSignUp({...good,preferredLanguage:"KR"}),null));test("bad username",()=>assert.equal(validateSignUp({...good,username:"!"}),"invalid_username"));test("bad email",()=>assert.equal(validateSignUp({...good,email:"x"}),"invalid_email"));test("weak pass",()=>assert.equal(validateSignUp({...good,password:"short",confirmPassword:"short"}),"weak_password"));test("mismatch",()=>assert.equal(validateSignUp({...good,confirmPassword:"different"}),"password_mismatch"));test("zh pref",()=>assert.equal(validateSignUp({...good,preferredLanguage:"zh"}),"invalid_language"));test("missing pref",()=>assert.equal(validateSignUp({...good,preferredLanguage:null}),"invalid_language"));test("login valid",()=>assert.equal(validateSignIn({email:"a@b.com",password:"x",language:"CN",returnTo:"/"}),null));test("login email",()=>assert.equal(validateSignIn({email:"x",password:"x",language:"CN",returnTo:"/"}),"invalid_email"));test("login empty",()=>assert.equal(validateSignIn({email:"a@b.com",password:"",language:"CN",returnTo:"/"}),"invalid_password"));test("login lang",()=>assert.equal(validateSignIn({email:"a@b.com",password:"x",language:"zh",returnTo:"/"}),"invalid_language"));
test("reason missing_code",()=>assert.equal(isAuthErrorReason("missing_code"),true));
test("reason configuration",()=>assert.equal(isAuthErrorReason("configuration"),true));
test("reason verification_failed",()=>assert.equal(isAuthErrorReason("verification_failed"),true));
test("reason invalid_link",()=>assert.equal(isAuthErrorReason("invalid_link"),true));
test("reason secret invalid",()=>assert.equal(isAuthErrorReason("secret_internal_code"),false));
test("reason undefined invalid",()=>assert.equal(isAuthErrorReason(undefined),false));
test("reason empty invalid",()=>assert.equal(isAuthErrorReason(""),false));
test("valid email accepted",()=>assert.equal(isValidEmail("person@example.com"),true));
test("invalid email rejected",()=>assert.equal(isValidEmail("not-an-email"),false));
test("resend CN valid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"CN"}),null));
test("resend KR valid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"KR"}),null));
test("resend zh invalid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"zh"}),"invalid_language"));
test("resend bad email",()=>assert.equal(validateResendConfirmation({email:"invalid",language:"CN"}),"invalid_email"));
test("profile rejects empty display name",()=>assert.equal(validateProfileUpdate({displayName:"   ",bio:"",preferredLanguage:"CN"}).error,"invalid_display_name"));
test("profile rejects display name over 50 characters",()=>assert.equal(validateProfileUpdate({displayName:"a".repeat(51),bio:"",preferredLanguage:"CN"}).error,"invalid_display_name"));
test("profile rejects bio over 500 characters",()=>assert.equal(validateProfileUpdate({displayName:"Name",bio:"a".repeat(501),preferredLanguage:"CN"}).error,"invalid_bio"));
test("profile rejects non CN KR preferred language",()=>assert.equal(validateProfileUpdate({displayName:"Name",bio:"",preferredLanguage:"zh"}).error,"invalid_language"));
test("profile update does not accept a client user id",()=>assert.equal("userId" in validateProfileUpdate({displayName:"Name",bio:"",preferredLanguage:"CN"}),false));
test("profile settings return path stays internal",()=>assert.equal(safeReturnTo("https://evil.example/settings/profile"),"/"));
test("public profile selection excludes private fields",()=>{assert.equal(PUBLIC_PROFILE_FIELDS.includes("email"),false);assert.equal(PUBLIC_PROFILE_FIELDS.includes("id"),false);assert.equal(PUBLIC_PROFILE_FIELDS.includes("updated_at"),false);});
test("missing profile username is route safe false",()=>assert.equal(isSafeUsername("?"),false));
test("username route rejects traversal",()=>assert.equal(isSafeUsername("../account"),false));
test("username route allows KCNY username",()=>assert.equal(isSafeUsername("test_user"),true));
test("public profile avatar uses display name first character",()=>assert.equal(profileAvatarInitial({display_name:"김민지",username:"minji"}),"김"));

test("user menu CN labels",()=>assert.equal(userMenuLabels("CN").profile,"我的主页"));
test("user menu KR labels",()=>assert.equal(userMenuLabels("KR").settings,"프로필 편집"));
test("user menu profile link encodes a valid username",()=>assert.equal(userMenuProfileHref("test_user"),"/u/test_user"));
test("user menu missing username has no profile link",()=>assert.equal(userMenuProfileHref(undefined),undefined));
test("user menu rejects unsafe profile usernames",()=>assert.equal(userMenuProfileHref("../unsafe"),undefined));
test("user menu avatar uses display name first",()=>assert.equal(userMenuAvatarInitial("测试名","fallback"),"测"));
test("user menu avatar falls back to username",()=>assert.equal(userMenuAvatarInitial("","minji"),"m"));
test("user menu avatar final fallback is K",()=>assert.equal(userMenuAvatarInitial(),"K"));
test("user menu is initially aria collapsed",()=>assert.equal(userMenuButtonState(false)["aria-expanded"],false));
test("user menu exposes menu popup semantics",()=>assert.equal(userMenuButtonState(false)["aria-haspopup"],"menu"));
test("user menu closes on Escape",()=>assert.equal(shouldCloseUserMenuForKey("Escape"),true));
test("user menu ignores ordinary keys",()=>assert.equal(shouldCloseUserMenuForKey("Enter"),false));
test("user menu signout remains a POST submit without closing before submission",()=>{const source=readFileSync(new URL("../components/UserMenu.tsx",import.meta.url),"utf8");assert.match(source,/<form action="\/auth\/signout" method="post"><button role="menuitem" type="submit">/);assert.doesNotMatch(source,/<button role="menuitem" type="submit" onClick=/);});
test("post accepts trimmed CN input",()=>assert.equal(validatePostInput({title:" Title ",content:" Content ",category:"culture",language:"CN"}).error,null));
test("post accepts KR input",()=>assert.equal(validatePostInput({title:"제목",content:"내용",category:"study",language:"KR"}).error,null));
test("post rejects empty title",()=>assert.equal(validatePostInput({title:" ",content:"content",language:"CN"}).error,"invalid_title"));
test("post rejects title over 120",()=>assert.equal(validatePostInput({title:"a".repeat(121),content:"content",language:"CN"}).error,"invalid_title"));
test("post rejects empty content",()=>assert.equal(validatePostInput({title:"title",content:" ",language:"CN"}).error,"invalid_content"));
test("post rejects content over 5000",()=>assert.equal(validatePostInput({title:"title",content:"a".repeat(5001),language:"CN"}).error,"invalid_content"));
test("post rejects zh language",()=>assert.equal(validatePostInput({title:"title",content:"content",category:"culture",language:"zh"}).error,"invalid_language"));
test("post UUID route accepts UUID",()=>assert.equal(isSafePostId("550e8400-e29b-41d4-a716-446655440000"),true));
test("post UUID route rejects traversal",()=>assert.equal(isSafePostId("../posts"),false));
test("post avatar uses display name",()=>assert.equal(postAvatarInitial({display_name:"Name",username:"user"}),"N"));
test("post avatar falls back to username",()=>assert.equal(postAvatarInitial({display_name:null,username:"user"}),"u"));
test("post rejects missing category",()=>assert.equal(validatePostInput({title:"title",content:"content",category:null,language:"CN"}).error,"invalid_category"));
test("post rejects invalid category",()=>assert.equal(validatePostInput({title:"title",content:"content",category:"news",language:"CN"}).error,"invalid_category"));
test("all six post categories are accepted",()=>assert.equal(POST_CATEGORIES.every((category)=>isPostCategory(category)),true));
test("post input preserves category separately from language",()=>{const result=validatePostInput({title:"title",content:"content",category:"travel",language:"KR"});assert.equal(result.error,null);if(!result.error){assert.equal(result.category,"travel");assert.equal(result.language,"KR");}});
test("CN category label is correct",()=>assert.equal(postCategoryLabel("culture","CN"),"文化交流"));
test("KR category label is correct",()=>assert.equal(postCategoryLabel("study","KR"),"유학 생활"));
test("CN post language label uses Chinese",()=>assert.equal(postLanguageLabel("CN","CN"),"中文"));
test("KR interface translates a CN post language",()=>assert.equal(postLanguageLabel("CN","KR"),"중국어"));
test("KR interface preserves KR post language",()=>assert.equal(postLanguageLabel("KR","KR"),"한국어"));
const postMigration=readFileSync(new URL("../supabase/migrations/202607290001_create_posts.sql",import.meta.url),"utf8");
test("posts migration contains category field",()=>assert.match(postMigration,/category text not null/i));
test("posts migration constrains all categories",()=>assert.match(postMigration,/category in \('culture', 'language', 'travel', 'study', 'daily', 'other'\)/));
test("posts migration has category created_at index",()=>assert.match(postMigration,/posts_category_created_at_desc_idx[\s\S]*\(category, created_at desc\)/));
test("posts migration keeps title content language checks",()=>{assert.match(postMigration,/char_length\(trim\(title\)\) between 1 and 120/);assert.match(postMigration,/char_length\(trim\(content\)\) between 1 and 5000/);assert.match(postMigration,/language in \('CN', 'KR'\)/);});
test("posts migration has no destructive SQL",()=>assert.equal(/\b(drop|truncate)\b/i.test(postMigration),false));
test("post category is a public post field",()=>assert.equal("category" in {category:"culture"},true));
test("delete confirmation remains a POST form contract",()=>assert.equal("post".toUpperCase(),"POST"));
const homeSource=readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");const detailSource=readFileSync(new URL("../app/posts/[id]/page.tsx",import.meta.url),"utf8");const profileSource=readFileSync(new URL("../app/u/[username]/page.tsx",import.meta.url),"utf8");const detailClientSource=readFileSync(new URL("../components/PostDetailClient.tsx",import.meta.url),"utf8");
const commentsMigration=readFileSync(new URL("../supabase/migrations/202607290002_create_comments.sql",import.meta.url),"utf8");
test("comment rejects empty content",()=>assert.equal(validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:"",language:"CN"}).error,"invalid_comment"));
test("comment rejects whitespace content",()=>assert.equal(validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:"   ",language:"CN"}).error,"invalid_comment"));
test("comment rejects content over 1000",()=>assert.equal(validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:"a".repeat(1001),language:"CN"}).error,"invalid_comment"));
test("comment accepts 1000 characters",()=>assert.equal(validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:"a".repeat(1000),language:"KR"}).error,null));
test("comment rejects invalid post id",()=>assert.equal(validateCommentInput({postId:"../post",content:"hello",language:"CN"}).error,"invalid_post"));
test("comment rejects invalid language",()=>assert.equal(validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:"hello",language:"zh"}).error,"invalid_language"));
test("comment input trims content",()=>{const r=validateCommentInput({postId:"550e8400-e29b-41d4-a716-446655440000",content:" hello ",language:"CN"});assert.equal(r.error,null);if(!r.error)assert.equal(r.value.content,"hello");});
test("comment avatar fallback",()=>assert.equal(commentAvatarInitial({displayName:null,username:"user"}),"u"));
test("comment count CN",()=>assert.equal(commentCountLabel(3,"CN"),"3 条评论"));
test("comment count KR",()=>assert.equal(commentCountLabel(3,"KR"),"댓글 3"));
test("public comments omit author id",()=>{const r=toPublicComments([{id:"550e8400-e29b-41d4-a716-446655440000",post_id:"550e8400-e29b-41d4-a716-446655440000",author_id:"author",content:"hello",created_at:"2026-01-01T00:00:00.000Z",author:{username:"user",display_name:null}}],"author")[0];assert.equal("author_id" in r,false);assert.equal(r.canDelete,true);});
test("comments migration creates table",()=>assert.match(commentsMigration,/create table if not exists public\.comments/i));
test("comments migration cascades post deletion",()=>assert.match(commentsMigration,/post_id uuid not null references public\.posts\(id\) on delete cascade/i));
test("comments migration validates content",()=>assert.match(commentsMigration,/char_length\(trim\(content\)\) between 1 and 1000/i));
test("comments migration has indexes",()=>{assert.match(commentsMigration,/comments_post_id_created_at_idx/);assert.match(commentsMigration,/comments_author_id_created_at_idx/);});
test("comments migration has no destructive SQL",()=>assert.equal(/\b(drop|truncate)\b/i.test(commentsMigration),false));
test("comments migration enables RLS",()=>assert.match(commentsMigration,/alter table public\.comments enable row level security/i));
test("comments RLS authenticated insert",()=>assert.match(commentsMigration,/for insert to authenticated[\s\S]*author_id = auth\.uid\(\)/i));
test("comments RLS author delete",()=>assert.match(commentsMigration,/for delete to authenticated[\s\S]*author_id = auth\.uid\(\)/i));
test("comments migration has no update policy",()=>assert.doesNotMatch(commentsMigration,/for update/i));
test("comment action uses session claims only",()=>{const s=readFileSync(new URL("../app/posts/[id]/comment-actions.ts",import.meta.url),"utf8");assert.match(s,/auth\.getClaims\(\)/);assert.doesNotMatch(s,/service_role|auth\.admin/i);});
test("comment insert only uses allowed fields",()=>{const s=readFileSync(new URL("../app/posts/[id]/comment-actions.ts",import.meta.url),"utf8");assert.match(s,/post_id: validation\.value\.postId[\s\S]*author_id: userId[\s\S]*content: validation\.value\.content/);});
test("comment delete scopes id post and user",()=>{const s=readFileSync(new URL("../app/posts/[id]/comment-actions.ts",import.meta.url),"utf8");assert.match(s,/\.eq\("id", commentId\)[\s\S]*\.eq\("post_id", postId\)[\s\S]*\.eq\("author_id", userId\)/);});
test("comment delete is a server action form",()=>{const s=readFileSync(new URL("../components/PostDetailClient.tsx",import.meta.url),"utf8");assert.match(s,/form action=\{deleteComment\}/);assert.doesNotMatch(s,/window\.confirm|alert\(/);});
test("comment query is ascending and limited",()=>assert.match(detailSource,/\.order\("created_at", \{ ascending: true \}\)[\s\S]*\.limit\(100\)/));
test("home uses comment aggregate",()=>assert.match(homeSource,/comments\(count\)/));
test("profile uses comment aggregate",()=>assert.match(profileSource,/comments\(count\)/));
test("comment UI avoids dangerous HTML",()=>assert.doesNotMatch(detailClientSource,/dangerouslySetInnerHTML/));
test("comment UI includes CN KR copy",()=>{assert.match(detailClientSource,/登录后参与评论/);assert.match(detailClientSource,/로그인 후 댓글을 작성할 수 있습니다/);});
test("home query includes category",()=>assert.match(homeSource,/title, content, category, language, created_at/));
test("detail query includes category",()=>assert.match(detailSource,/title, content, category, language, created_at/));
test("profile query includes category",()=>assert.match(profileSource,/title, content, category, language, created_at/));
test("delete uses a second confirmation state",()=>{assert.match(detailClientSource,/confirming/);assert.match(detailClientSource,/确认删除/);assert.match(detailClientSource,/type="submit"/);assert.doesNotMatch(detailClientSource,/window\.confirm|alert\(/);});
