import test from "node:test";import assert from "node:assert/strict";import {isLanguage,normalizeLanguage,safeReturnTo,validateSignUp,validateSignIn,validateResendConfirmation,isValidEmail,isAuthErrorReason} from "../lib/auth.ts";import {isSafeUsername,profileAvatarInitial,PUBLIC_PROFILE_FIELDS,validateProfileUpdate} from "../lib/profile.ts";import {shouldCloseUserMenuForKey,userMenuAvatarInitial,userMenuButtonState,userMenuLabels,userMenuProfileHref} from "../lib/user-menu.ts";
test("CN valid",()=>assert.equal(isLanguage("CN"),true));test("KR valid",()=>assert.equal(isLanguage("KR"),true));test("zh invalid",()=>assert.equal(isLanguage("zh"),false));test("ko invalid",()=>assert.equal(isLanguage("ko"),false));test("en invalid",()=>assert.equal(isLanguage("en"),false));test("null invalid",()=>assert.equal(isLanguage(null),false));test("normalize KR",()=>assert.equal(normalizeLanguage("KR"),"KR"));test("normalize CN",()=>assert.equal(normalizeLanguage("CN"),"CN"));test("normalize unknown",()=>assert.equal(normalizeLanguage("x"),"CN"));
for(const [n,v,e] of [["root","/","/"],["profile","/profile","/profile"],["query","/a?x=1","/a?x=1"],["slashes","//evil","/"],["https","https://evil","/"],["http","http://evil","/"],["backslash","/\\evil","/"],["control","/a\n","/"],["encoded","/%2f%2fevil","/"],["double","/%252f%252fevil","/"],["empty","","/"],["null",null,"/"]])test(`return ${n}`,()=>assert.equal(safeReturnTo(v),e));
const good={username:"valid_user",displayName:"Name",email:"a@b.com",password:"password1",confirmPassword:"password1",preferredLanguage:"CN"};test("signup CN",()=>assert.equal(validateSignUp(good),null));test("signup KR",()=>assert.equal(validateSignUp({...good,preferredLanguage:"KR"}),null));test("bad username",()=>assert.equal(validateSignUp({...good,username:"!"}),"invalid_username"));test("bad email",()=>assert.equal(validateSignUp({...good,email:"x"}),"invalid_email"));test("weak pass",()=>assert.equal(validateSignUp({...good,password:"short",confirmPassword:"short"}),"weak_password"));test("mismatch",()=>assert.equal(validateSignUp({...good,confirmPassword:"different"}),"password_mismatch"));test("zh pref",()=>assert.equal(validateSignUp({...good,preferredLanguage:"zh"}),"invalid_language"));test("missing pref",()=>assert.equal(validateSignUp({...good,preferredLanguage:null}),"invalid_language"));test("login valid",()=>assert.equal(validateSignIn({email:"a@b.com",password:"x",language:"CN",returnTo:"/"}),null));test("login email",()=>assert.equal(validateSignIn({email:"x",password:"x",language:"CN",returnTo:"/"}),"invalid_email"));test("login empty",()=>assert.equal(validateSignIn({email:"a@b.com",password:"",language:"CN",returnTo:"/"}),"invalid_password"));test("login lang",()=>assert.equal(validateSignIn({email:"a@b.com",password:"x",language:"zh",returnTo:"/"}),"invalid_language"));
test("reason missing_code",()=>assert.equal(isAuthErrorReason("missing_code"),true));
test("reason configuration",()=>assert.equal(isAuthErrorReason("configuration"),true));
test("reason verification_failed",()=>assert.equal(isAuthErrorReason("verification_failed"),true));
test("reason invalid_link",()=>assert.equal(isAuthErrorReason("invalid_link"),true));
test("reason secret invalid",()=>assert.equal(isAuthErrorReason("secret_internal_code"),false));
test("reason undefined invalid",()=>assert.equal(isAuthErrorReason(undefined),false));
test("reason empty invalid",()=>assert.equal(isAuthErrorReason(""),false));
test("valid email accepted",()=>assert.equal(isValidEmail("person@example.com"),true));
test("invalid email rejected",()=>assert.equal(isValidEmail("not-an-email"),false));
test("resend CN valid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"CN"}),null));
test("resend KR valid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"KR"}),null));
test("resend zh invalid",()=>assert.equal(validateResendConfirmation({email:"person@example.com",language:"zh"}),"invalid_language"));
test("resend bad email",()=>assert.equal(validateResendConfirmation({email:"invalid",language:"CN"}),"invalid_email"));
test("profile rejects empty display name",()=>assert.equal(validateProfileUpdate({displayName:"   ",bio:"",preferredLanguage:"CN"}).error,"invalid_display_name"));
test("profile rejects display name over 50 characters",()=>assert.equal(validateProfileUpdate({displayName:"a".repeat(51),bio:"",preferredLanguage:"CN"}).error,"invalid_display_name"));
test("profile rejects bio over 500 characters",()=>assert.equal(validateProfileUpdate({displayName:"Name",bio:"a".repeat(501),preferredLanguage:"CN"}).error,"invalid_bio"));
test("profile rejects non CN KR preferred language",()=>assert.equal(validateProfileUpdate({displayName:"Name",bio:"",preferredLanguage:"zh"}).error,"invalid_language"));
test("profile update does not accept a client user id",()=>assert.equal("userId" in validateProfileUpdate({displayName:"Name",bio:"",preferredLanguage:"CN"}),false));
test("profile settings return path stays internal",()=>assert.equal(safeReturnTo("https://evil.example/settings/profile"),"/"));
test("public profile selection excludes private fields",()=>{assert.equal(PUBLIC_PROFILE_FIELDS.includes("email"),false);assert.equal(PUBLIC_PROFILE_FIELDS.includes("id"),false);assert.equal(PUBLIC_PROFILE_FIELDS.includes("updated_at"),false);});
test("missing profile username is route safe false",()=>assert.equal(isSafeUsername("?"),false));
test("username route rejects traversal",()=>assert.equal(isSafeUsername("../account"),false));
test("username route allows KCNY username",()=>assert.equal(isSafeUsername("test_user"),true));
test("public profile avatar uses display name first character",()=>assert.equal(profileAvatarInitial({display_name:"김민지",username:"minji"}),"김"));

test("user menu CN labels",()=>assert.equal(userMenuLabels("CN").profile,"我的主页"));
test("user menu KR labels",()=>assert.equal(userMenuLabels("KR").settings,"프로필 편집"));
test("user menu profile link encodes a valid username",()=>assert.equal(userMenuProfileHref("test_user"),"/u/test_user"));
test("user menu missing username has no profile link",()=>assert.equal(userMenuProfileHref(undefined),undefined));
test("user menu rejects unsafe profile usernames",()=>assert.equal(userMenuProfileHref("../unsafe"),undefined));
test("user menu avatar uses display name first",()=>assert.equal(userMenuAvatarInitial("测试名","fallback"),"测"));
test("user menu avatar falls back to username",()=>assert.equal(userMenuAvatarInitial("","minji"),"m"));
test("user menu avatar final fallback is K",()=>assert.equal(userMenuAvatarInitial(),"K"));
test("user menu is initially aria collapsed",()=>assert.equal(userMenuButtonState(false)["aria-expanded"],false));
test("user menu exposes menu popup semantics",()=>assert.equal(userMenuButtonState(false)["aria-haspopup"],"menu"));
test("user menu closes on Escape",()=>assert.equal(shouldCloseUserMenuForKey("Escape"),true));
test("user menu ignores ordinary keys",()=>assert.equal(shouldCloseUserMenuForKey("Enter"),false));
