"use client";

import { useState } from "react";
import { createComment, createCommentReply, deleteComment } from "@/app/posts/[id]/comment-actions";
import { deletePost } from "@/app/posts/actions";
import { Header } from "@/components/Header";
import { LikeButton } from "@/components/LikeButton";
import { BookmarkButton } from "@/components/BookmarkButton";
import { commentAvatarInitial, commentCountLabel, replyTargetUsername, type CommentThread, type PublicComment } from "@/lib/comments";
import type { Language } from "@/lib/auth";
import { formatPostDate, postAvatarInitial, postCategoryLabel, postLanguageLabel, type PublicPost } from "@/lib/posts";

type Props = { post: PublicPost; commentThreads: CommentThread[]; commentCount: number; commentsUnavailable: boolean; language: Language; authenticated: boolean; currentUsername?: string; currentDisplayName?: string; canEdit: boolean; canDelete: boolean; };

export function PostDetailClient({ post, commentThreads, commentCount, commentsUnavailable, language, authenticated, currentUsername, currentDisplayName, canEdit, canDelete }: Props) {
  const [activeLanguage, setActiveLanguage] = useState(language);
  const korean = activeLanguage === "KR";
  const author = post.author;
  if (!author) return null;
  return <main><Header language={activeLanguage} onLanguageChange={setActiveLanguage} authenticated={authenticated} username={currentUsername} displayName={currentDisplayName} /><section className="shell post-detail-page"><article className="post-detail-card"><div className="post-detail-author"><div className="avatar coral" aria-hidden="true">{postAvatarInitial(author)}</div><div><a href={`/u/${encodeURIComponent(author.username)}?lang=${activeLanguage}`}>{author.display_name || author.username}</a><p>@{author.username} · {formatPostDate(post.created_at, activeLanguage)}</p></div></div><p className="post-language">{postCategoryLabel(post.category, activeLanguage)} · {postLanguageLabel(post.language, activeLanguage)}</p><h1>{post.title}</h1><p className="post-detail-content">{post.content}</p><div className="post-detail-actions"><LikeButton postId={post.id} likeCount={post.likeCount} liked={post.likedByCurrentUser} language={activeLanguage} returnTo={`/posts/${encodeURIComponent(post.id)}?lang=${activeLanguage}`} authenticated={authenticated} /><BookmarkButton postId={post.id} bookmarked={post.bookmarkedByCurrentUser} language={activeLanguage} returnTo={`/posts/${encodeURIComponent(post.id)}?lang=${activeLanguage}`} authenticated={authenticated} /></div>{(canEdit || canDelete) && <div className="post-owner-actions">{canEdit && <a className="button secondary" href={`/posts/${encodeURIComponent(post.id)}/edit?lang=${activeLanguage}`}>{korean ? "게시글 수정" : "编辑帖子"}</a>}{canDelete && <DeletePostControl postId={post.id} language={activeLanguage} korean={korean} />}</div>}</article><section id="comments" className="comments-section" aria-label={korean ? "댓글" : "评论"}><h2>{commentCountLabel(commentCount, activeLanguage)}</h2>{authenticated ? <CommentComposer postId={post.id} language={activeLanguage} korean={korean} /> : <SignInToComment postId={post.id} language={activeLanguage} korean={korean} />}{commentsUnavailable ? <p className="comments-message">{korean ? "댓글을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요." : "暂时无法加载评论，请稍后再试。"}</p> : commentCount === 0 ? <p className="comments-message">{korean ? "아직 댓글이 없습니다. 첫 댓글을 남겨 보세요." : "还没有评论，来留下第一条吧。"}</p> : <div className="comment-list">{commentThreads.map((thread) => <CommentThreadCard key={thread.comment.id} thread={thread} language={activeLanguage} authenticated={authenticated} />)}</div>}</section></section></main>;
}

function SignInToComment({ postId, language, korean }: { postId: string; language: Language; korean: boolean }) { return <div className="comment-signin"><p>{korean ? "로그인 후 댓글을 작성할 수 있습니다. 답글도 작성할 수 있습니다." : "登录后参与评论。也可以发表回复。"}</p><a className="button secondary" href={`/auth/login?lang=${language}&returnTo=${encodeURIComponent(`/posts/${postId}`)}`}>{korean ? "로그인" : "登录"}</a></div>; }
function CommentComposer({ postId, language, korean }: { postId: string; language: Language; korean: boolean }) { const [content, setContent] = useState(""); const [pending, setPending] = useState(false); return <form className="comment-composer" action={createComment} onSubmit={() => setPending(true)}><input type="hidden" name="postId" value={postId} /><input type="hidden" name="language" value={language} /><label htmlFor="comment-content">{korean ? "댓글 작성" : "发表评论"}</label><textarea id="comment-content" name="content" value={content} onChange={(event) => setContent(event.target.value)} placeholder={korean ? "댓글을 입력해 주세요." : "写下你的评论…"} maxLength={1000} required /><div className="comment-composer-bottom"><span>{korean ? "최대 1000자" : "最多 1000 字"}</span><button type="submit" className="button primary" disabled={pending || content.trim().length === 0}>{pending ? (korean ? "등록 중…" : "发布中…") : (korean ? "댓글 등록" : "发布评论")}</button></div></form>; }
function CommentThreadCard({ thread, language, authenticated }: { thread: CommentThread; language: Language; authenticated: boolean }) { const [replying, setReplying] = useState(false); const korean = language === "KR"; const replyTarget = replyTargetUsername(thread.comment); return <article className="comment-thread"><CommentCard comment={thread.comment} language={language} replyCount={thread.replies.length} /><div className="comment-actions">{authenticated ? <button type="button" className="comment-reply-trigger" onClick={() => setReplying((value) => !value)} aria-expanded={replying}>{korean ? "답글" : "回复"}</button> : <a className="comment-reply-trigger" href={`/auth/login?lang=${language}&returnTo=${encodeURIComponent(`/posts/${thread.comment.postId}`)}`}>{korean ? "답글" : "回复"}</a>}</div>{replying && <ReplyComposer postId={thread.comment.postId} parentCommentId={thread.comment.id} language={language} korean={korean} onCancel={() => setReplying(false)} />}{thread.replies.length > 0 ? <div className="comment-replies">{thread.replies.map((reply) => <CommentCard key={reply.id} comment={reply} language={language} reply replyTargetUsername={replyTarget} />)}</div> : <p className="no-replies">{korean ? "아직 답글이 없습니다." : "暂无回复。"}</p>}</article>; }
function ReplyComposer({ postId, parentCommentId, language, korean, onCancel }: { postId: string; parentCommentId: string; language: Language; korean: boolean; onCancel: () => void }) { const [content, setContent] = useState(""); const [pending, setPending] = useState(false); return <form className="reply-composer" action={createCommentReply} onSubmit={() => setPending(true)}><input type="hidden" name="postId" value={postId} /><input type="hidden" name="parentCommentId" value={parentCommentId} /><input type="hidden" name="language" value={language} /><label htmlFor={`reply-${parentCommentId}`}>{korean ? "답글 작성" : "发表回复"}</label><textarea id={`reply-${parentCommentId}`} name="content" value={content} onChange={(event) => setContent(event.target.value)} maxLength={1000} required /><div className="comment-composer-bottom"><span>{korean ? "최대 1000자" : "最多 1000 字"}</span><div className="reply-buttons"><button type="button" className="button secondary" onClick={onCancel} disabled={pending}>{korean ? "취소" : "取消"}</button><button type="submit" className="button primary" disabled={pending || content.trim().length === 0}>{pending ? (korean ? "등록 중…" : "发布中…") : (korean ? "답글 작성" : "发表回复")}</button></div></div></form>; }
function CommentCard({ comment, language, replyCount, reply = false, replyTargetUsername }: { comment: PublicComment; language: Language; replyCount?: number; reply?: boolean; replyTargetUsername?: string }) { const [confirming, setConfirming] = useState(false); const korean = language === "KR"; const deleteLabel = reply ? (korean ? "답글 삭제" : "删除回复") : (korean ? "댓글 삭제" : "删除评论"); const deletePrompt = reply ? (korean ? "이 답글을 삭제하시겠습니까?" : "确定删除这条回复吗？") : (korean ? "이 댓글을 삭제하시겠습니까?" : "确定删除这条评论吗？"); return <article className={`comment-card${reply ? " comment-reply" : ""}`}><div className="avatar blue" aria-hidden="true">{commentAvatarInitial(comment.author)}</div><div className="comment-main"><div className="comment-meta"><a href={`/u/${encodeURIComponent(comment.author.username)}?lang=${language}`}>{comment.author.displayName || comment.author.username}</a><span>@{comment.author.username}</span><span>·</span><time>{formatPostDate(comment.createdAt, language)}</time></div>{reply && replyTargetUsername ? <p className="replying-to">{korean ? `@${replyTargetUsername}님에게 답글` : `回复 @${replyTargetUsername}`}</p> : null}<p>{comment.content}</p>{comment.canDelete && (confirming ? <section className="delete-confirmation" aria-live="polite"><p>{deletePrompt}{!reply && replyCount ? ` ${korean ? "이 댓글을 삭제하면 아래 답글도 함께 삭제됩니다." : "删除这条评论也会删除它下面的回复。"}` : ""}</p><div><button type="button" className="button secondary" onClick={() => setConfirming(false)}>{korean ? "취소" : "取消"}</button><form action={deleteComment}><input type="hidden" name="commentId" value={comment.id} /><input type="hidden" name="postId" value={comment.postId} /><input type="hidden" name="language" value={language} /><button type="submit" className="delete-post">{korean ? "삭제 확인" : "确认删除"}</button></form></div></section> : <button type="button" className="comment-delete" onClick={() => setConfirming(true)}>{deleteLabel}</button>)}</div></article>; }
function DeletePostControl({ postId, language, korean }: { postId: string; language: Language; korean: boolean }) { const [confirming, setConfirming] = useState(false); if (!confirming) return <button type="button" className="delete-post" onClick={() => setConfirming(true)}>{korean ? "게시글 삭제" : "删除帖子"}</button>; return <section className="delete-confirmation" aria-live="polite"><p>{korean ? "이 게시글을 정말 삭제할까요? 이 작업은 되돌릴 수 없습니다." : "确定删除这篇帖子吗？此操作无法恢复。"}</p><div><button type="button" className="button secondary" onClick={() => setConfirming(false)}>{korean ? "취소" : "取消"}</button><form action={deletePost}><input type="hidden" name="postId" value={postId} /><input type="hidden" name="language" value={language} /><button type="submit" className="delete-post">{korean ? "삭제 확인" : "确认删除"}</button></form></div></section>; }
